use alloc::format;
use cargo_metadata::MetadataCommand;
use std::println;
use std::string::String;
use std::string::ToString;
use std::vec::Vec;
use std::{
    cmp::max,
    env::var,
    fs::{read_to_string, write},
    path::Path,
};
use syn::{
    Expr, Lit,
    punctuated::Punctuated,
    visit::{Visit, visit_macro},
};

struct PinLog {
    name: String,
    location: String, // "relative/path/to/file.rs:42"
}

pub fn scan_source_for_pin_logs(human_file_path: &Path) {
    let metadata = MetadataCommand::new()
        .no_deps()
        .exec()
        .expect("cargo metadata failed");

    let workspace_root = metadata.workspace_root.as_std_path();
    let mut pin_logs: Vec<PinLog> = Vec::new();

    for package in metadata.workspace_packages() {
        let src_dir = package.manifest_path.parent().unwrap().join("src");
        if !src_dir.exists() {
            continue;
        }
        println!("cargo:rerun-if-changed={src_dir}");
        extract_pin_log_names_in_directory(src_dir.as_std_path(), workspace_root, &mut pin_logs);
    }

    let out_dir = var("OUT_DIR").unwrap();
    write_names_rust_file(&pin_logs, &Path::new(&out_dir).join("mark_names.rs"));
    write_names_human_file(&pin_logs, human_file_path);
}

fn extract_pin_log_names_in_directory(
    src_dir: &Path,
    workspace_root: &Path,
    pin_logs: &mut Vec<PinLog>,
) {
    for entry in walkdir::WalkDir::new(&src_dir)
        .sort_by_file_name()
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "rs"))
    {
        let relative_path = entry
            .path()
            .strip_prefix(workspace_root)
            .unwrap_or(entry.path())
            .display()
            .to_string();
        let Ok(content) = read_to_string(entry.path()) else {
            continue;
        };
        extract_pin_log_names(&content, &relative_path, pin_logs);
    }
}

fn write_names_rust_file(pin_logs: &[PinLog], path: &Path) {
    let entries: String = pin_logs
        .iter()
        .map(|pl| format!("{:?},", pl.name))
        .collect();
    let length = pin_logs.len();
    let code = format!("pub(crate) const NAMES: [&str; {length}] = [{entries}];");
    write(path, code).unwrap();
}

fn pin_state(n: usize, width: usize) -> String {
    format!("{n:0width$b}")
        .chars()
        .map(|c| c.to_string())
        .rev()
        .collect::<Vec<_>>()
        .join(" ")
}

fn pin_numbers(width: usize) -> String {
    (0..width)
        .map(|i| char::from_digit((i % 10) as u32, 10).unwrap().to_string())
        .collect::<Vec<_>>()
        .join(" ")
}

fn format_columns(
    col1: &str,
    col2: &str,
    col3: &str,
    col1_width: usize,
    col2_width: usize,
) -> String {
    format!("{col1:<col1_width$}  {col2:<col2_width$}  {col3}\n")
}

fn write_names_human_file(pin_logs: &[PinLog], path: &Path) {
    let bit_width = if pin_logs.is_empty() {
        1
    } else {
        pin_logs.len().ilog2() as usize + 1
    };

    let mut lines = String::new();
    lines.push_str("This file is automatically generated on each build\n");
    lines.push_str(
        "It shows the output pin states that corresponds to each pin_log! in your code\n\n",
    );

    let pn = pin_numbers(bit_width);
    let pins_col_label = "pins";
    let name_col_label = "name";
    let location_col_label = "location";
    let pins_col_width = max(pins_col_label.len(), pn.len());
    let name_col_width = max(
        name_col_label.len(),
        pin_logs.iter().map(|pl| pl.name.len()).max().unwrap_or(0),
    );
    let location_col_width = max(
        location_col_label.len(),
        pin_logs
            .iter()
            .map(|pl| pl.location.len())
            .max()
            .unwrap_or(0),
    );

    lines.push_str(&format_columns(&pn, "", "", pins_col_width, name_col_width));
    lines.push_str(&format_columns(
        pins_col_label,
        name_col_label,
        location_col_label,
        pins_col_width,
        name_col_width,
    ));
    lines.push_str(&format!(
        "{}\n",
        "-".repeat(pins_col_width + 2 + name_col_width + 2 + location_col_width)
    ));

    for (i, pl) in pin_logs.iter().enumerate() {
        lines.push_str(&format_columns(
            &pin_state(i + 1, bit_width),
            &pl.name,
            &pl.location,
            pins_col_width,
            name_col_width,
        ));
    }

    write(path, lines).unwrap();
}

fn extract_pin_log_names(content: &str, file: &str, pin_logs: &mut Vec<PinLog>) {
    if let Ok(parsed) = syn::parse_file(content) {
        Visitor { pin_logs, file }.visit_file(&parsed);
    }
}

struct Visitor<'a> {
    pin_logs: &'a mut Vec<PinLog>,
    file: &'a str,
}

impl<'ast> Visit<'ast> for Visitor<'_> {
    fn visit_macro(&mut self, mac: &'ast syn::Macro) {
        if mac
            .path
            .segments
            .last()
            .is_some_and(|s| s.ident == "pin_log")
        {
            let args = mac.parse_body_with(Punctuated::<Expr, syn::Token![,]>::parse_terminated);
            if let Ok(args) = args {
                if let Some(Expr::Lit(syn::ExprLit {
                    lit: Lit::Str(s), ..
                })) = args.first()
                {
                    let name = s.value();
                    let line = s.span().start().line;
                    let location = format!("{}:{}", self.file, line);
                    if !self.pin_logs.iter().any(|pl| pl.name == name) {
                        self.pin_logs.push(PinLog { name, location });
                    }
                }
            }
        }
        visit_macro(self, mac);
    }
}
